### PR TITLE
[SVN] maple plugin: enhancement

### PR DESCRIPTION
**Pull request by jgmbenoit**
This is a bunch of three patches that gradually improves the current maple plugin:
- the first patch fixes and refreshes the current maple plugin machinery;
- the second patch allows to read an `init-maple.mpl` maple script placed under the `TEXMACS_HOME_PATH` hierarchy;
- the third patch makes the current banner more informative.

### CODE REVIEW

**Comment by da-liii** [comment]
Just requested a code view from real users of the maple plugin, as I'm not the user of the Maple plugin, I need real users confirm and then commit your patch.

**Comment by Matthias-A-Steiner** [comment]
I ran the make-files as they were.

```
% make -f Makefile all
g++ src/tm_maple_5.cpp -o bin/tm_maple_5
```

worked fine. Yet tm_maple_9 is not compiled and I received a fatal error message on macOS 14.6.1.

```
% make -f Makefile.9 all
sed \
-e 's%${MAPLE}/$MAPLE_SYS_BIN/cmaple%/Users/tilda/.TeXmacs/bin/tm_maple_9%' \
-e 's%${MAPLE}/$MAPLE_SYS_BIN/maplew%/Users/tilda/.TeXmacs/bin/tm_maple_9%' \
/Library/Frameworks/Maple.framework/Versions/2024/bin/maple > /Users/tilda/.TeXmacs/bin/tm_maple_9.sh && chmod a+x /Users/tilda/.TeXmacs/bin/tm_maple_9.sh
```
```
gcc -L/Library/Frameworks/Maple.framework/Versions/2024/bin.APPLE_ARM64_MACOS -Wl,-rpath,/Library/Frameworks/Maple.framework/Versions/2024/bin.APPLE_ARM64_MACOS -I/Library/Frameworks/Maple.framework/Versions/2024/extern/include src.9/tm_maple_9.c -o /Users/tilda/.TeXmacs/bin/tm_maple_9 -lmaplec

src.9/tm_maple_9.c:19:10: fatal error: ‘argz.h’ file not found
#include <argz.h>
**^~~~~~~~**
1 error generated.
make: *** [/Users/tilda/.TeXmacs/bin/tm_maple_9] Error 1
```

Wonder where the `argz.h` file is supposed to be from. Hope this helps,

cheers, Tilda

**Comment by jgmbenoit** [comment]
Thanks checking. This issue concerns the third (and last) patch. It appears that the header `argz.h` does not belong to the set of [_C Standard Library header files_](https://en.cppreference.com/w/c/header) as the GCC documentation lets think [here](https://www.gnu.org/software/libc/manual/html_node/Argz-Functions.html) (line before the enumeration of the header functions). These are basically helper functions. My understanding is that you the GCC suite tools. If so, do you have any idea why you does not have this header ?

I am on my way to implement a more transportable code.

**Comment by Matthias-A-Steiner** [comment]
Thanks for your efforts, Jérôme. On my computer running under macOS 14.6.1 I have the following installed via MacPorts:

```
libgcc @8.0_0 (active)
libgcc13 @13.3.0_1+stdlib_flag (active)
libgcc14 @14.2.0_1+stdlib_flag (active)
```
However there's no file `argz.h` on my system.  I ran the `port info` command but they don't seem to have these libraries

```
% port info Gnulib
Error: Port Gnulib not found
% port info Gnulibc
Error: Port Gnulibc not found
% port info libc   
Error: Port libc not found
```

Maybe MacPorts list them under a different name, but I haven't found out yet.

By the way, your brushed-up `Makefile.9` runs smoothly with the previous version of the plugin.

Cheers, Tilda

**Comment by jgmbenoit** [comment]
Thanks for your prompt feedback, Matthias. It appears that, on my Debian box, the manpage about `argz` says in the section **CONFORMING TO** that "_[`argv`] functions are GNU extension_". So I guess that you `gcc` installation is strictly `iso`.  Otherwise, the current version of the maple plugin does not compile on my Debian box. This might be because the I play with a more recent version of Maple and/or the default compiler options on Debian are more strict. Whatever, I could rewrite an `iso` version of the involved my code. I am on my way to push it.

**Comment by jgmbenoit** [comment]
Here are the output a simple test:
[tm-pi-maple-informative_banner.pdf](https://github.com/user-attachments/files/16574105/tm-pi-maple-informative_banner.pdf)
[tm-pi-maple-informative_banner.tm.txt](https://github.com/user-attachments/files/16574106/tm-pi-maple-informative_banner.tm.txt)

**Comment by Matthias-A-Steiner** [comment]
Dear Jérôme, I successfully installed and compiled your iso-conforming version of `tm_maple_9.c` Next, I did your test runs and some basic differential and integral calculus task. Judging from that I think the plugin works fine. Yet the compiler issued a warning:


```
make -f Makefile.9 all
sed \
-e 's%${MAPLE}/$MAPLE_SYS_BIN/cmaple%/Users/tilda/.TeXmacs/bin/tm_maple_9%' \
-e 's%${MAPLE}/$MAPLE_SYS_BIN/maplew%/Users/tilda/.TeXmacs/bin/tm_maple_9%' \
/Library/Frameworks/Maple.framework/Versions/2024/bin/maple > /Users/tilda/.TeXmacs/bin/tm_maple_9.sh && chmod a+x /Users/tilda/.TeXmacs/bin/tm_maple_9.sh
gcc -L/Library/Frameworks/Maple.framework/Versions/2024/bin.APPLE_ARM64_MACOS -Wl,-rpath,/Library/Frameworks/Maple.framework/Versions/2024/bin.APPLE_ARM64_MACOS -I/Library/Frameworks/Maple.framework/Versions/2024/extern/include src.9/tm_maple_9.c -o /Users/tilda/.TeXmacs/bin/tm_maple_9 -lmaplec
src.9/tm_maple_9.c:100:55: warning: format specifies type 'char *' but the argument has type 'void *' [-Wformat]
    fprintf (stderr, "Syntax Error, %s\n> %s\n", msg, data);
                                          ~~          ^~~~
1 warning generated.
```

I cannot judge whether this error is critical or not. Maybe it could be fixed as well.

May I also ask you some questions?

- What exactly is OpenMaple and does the average Maple user need this API? 
- What is **tm_maple_5** needed for? Some outdated Version of Maple? 
- I'm still running on Maple 2024.0 – is Maple 2045.1 already out or is just beta?

Cheers, Tilda

**Comment by jgmbenoit** [comment]
Thanks for the feed back. These ae just noisy warnings. The following patch silences them.

**Comment by jgmbenoit** [comment]
> I'm still running on Maple 2024.0 – is Maple 2024.1 already out or is just beta?

`Maple 2024.1` is already out. You can the fetch the  Upgrader from Maplesoft  at their [_Downloads & Service Packs_](https://fr.maplesoft.com/support/downloads/index.aspx) webpage.

**Comment by jgmbenoit** [comment]
> What exactly is _OpenMaple_ and does the average Maple user need this API?

_OpenMaple_ is an opaque access to Maple from the compiled languages C and  Java. Alongside, through APIs built on top of the C API, it provides an access to the interpreted language Python3 and the compiled language Visual Basic. The 
_Command-line Interface_ and the  _Standard Worksheet Interface_ are built on it as well as the new Python interface.
So the _"average Maple users"_ use _OpenMaple_ but probably without knowing it. The _"advanced Maple users"_ may consider it for by-passing the use of an interface and save some resources. And they can design their own Maple interface if they are not happy with the provided ones. _OpenMaple_ is quite well documented in the `Maple Help` pages: the [Overview of OpenMaple](https://fr.maplesoft.com/support/help/maple/view.aspx?path=OpenMaple) page is a good start.

**Comment by Matthias-A-Steiner** [comment]
Dear Jérôme, I downloaded the "silenced" version of the plugin from your repo.  `tm_maple_9.c` now compiles with no complaints. Test runs were also successfully completed. In addition, matrices are now correctly displayed in a TeXmacs session. So, maybe your fix did more than just silencing the compiler ;-) . Thanks again for your work. 

I wonder whether I should report back to the _TeXmacs forum_  of your successful rewrite of the plugin, or should I rather wait 'till Darcy Shen will have committed your patch?

Cheers, Tilda

PS 1: Thanks for info on _OpenMaple_ and `tm_maple_5`.
PS 2: In the meantime I've also upgraded to Maple 2024.1 via the app(s). I just didn't notice that there has been an upgrade around as I have just been using `cli` Maple lately.

**Comment by jgmbenoit** [comment]
Thanks for the feed back. I have just uploaded  a patch that hardens the building machinery.
Let us wait. Having say that, I think that the _TeXmacs interface for Maple_ can be improved by sticking closer to the _C OpenMaple API_. I will have a closer look later.

**Pull request closed without merging**
