### PR TITLE
Haskell Plugin

### PR DESCRIPTION
**Pull request by BBratschiKirloskar**
Hi,
I just add a folder at texmacs/tree/master/plugins  for an Haskell Plugin, with all the files required for the installation. Everything seems to work well on Mac OS 10,14,6 with TeXmacs 1.99.11.
Maybe some minor adjustments are required for other OS.

Anyway, I let you decide what to do with it...

Bertrand

### CODE REVIEW

**Comment by BBratschiKirloskar** [comment]
The Haskell source for TeXmacsGhci can be fund is [this repository](https://github.com/BBratschiKirloskar/TeXmacsGhci).

**Comment by sadhen** [comment]
Thanks for your pull request.

But for plugins like Haskell, we need to take extra package steps to package it. I think it should be maintained outside GNU TeXmacs.

**Comment by sadhen** [comment]
> What extra package steps are you speaking about ?

@BBratschiKirloskar  I mean building the binary using ghc.

**Comment by mgubi** [comment]
I think we can host anyway the plugin in this GitHub project. That would be useful to centralise the informations.

**Comment by sadhen** [comment]
@BBratschiKirloskar 

Would you like join the TeXmacs community and host the haskell plugin under http://github.com/texmacs

I hosted the Scala plugin for TeXmacs in https://github.com/texmacs/TeXmacs.scala

**Comment by BBratschiKirloskar** [comment]
> @BBratschiKirloskar
> 
> Would you like join the TeXmacs community and host the haskell plugin under [http://github.com/texmacs](https://github.com/texmacs)
> 
Yes, with pleasure.

**Comment by sadhen** [comment]
@BBratschiKirloskar  I have invited you as a member to this group.

You may fork your project to this group.

**Comment by sadhen** [comment]
@BBratschiKirloskar  I've forked it to https://github.com/texmacs/TeXmacsGhci .

And I'm also interested in the Haskell plugin. If I have time, I'd like to create pull request to the Haskell plugin. We may support Haskell language syntax highlight later.

https://lists.gnu.org/archive/html/texmacs-dev/2020-03/msg00012.html

Here are some progresses on parsers for Programming Languages.

**Comment by sadhen** [comment]
@mgubi  For tm_jupyter, I also forked it to this group.

**Pull request closed without merging**
