### PR TITLE
Build on M1 Monterey

### PR DESCRIPTION
**Pull request by ProfFan**
This is current not really mergable, but I don't really have time to cleanup.

### CODE REVIEW

**Comment by darcy-shen** [comment]
Thanks! Part of the pull requests has been merged now. Another part of this pr tries to resolve CMake link issues introduced by #59 . I will take care of this issue.

**Comment by woutersj** [comment]
The commit has broken building on Linux. There are two more `oultines` to rename, see #62 .

**Comment by darcy-shen** [comment]
Yes, I only verified that it works on macOS. Perhaps, Github actions should be enabled to execute tests on all available platforms.

**Comment by woutersj** [comment]
Continuous builds would be great, I also don't have any other way to test on macOS.
I don't know how this compares to Github Actions, but I've previously set up a linux build on Travis. They also provide macOS.
https://github.com/woutersj/texmacs/blob/travis/.travis.yml

**Comment by ProfFan** [comment]
Actions CI would definitely be a great addition.

**Pull request closed without merging**
