### PR TITLE
Fix build with Qt 5.15

### PR DESCRIPTION
**Pull request by rezso**

### CODE REVIEW

**Comment by sadhen** [comment]
Is this PR work for Qt 4.

**Comment by PikachuHy** [comment]
I just test this pr in Qt5, it works well.
For Qt4, there is no qt4 package in my msys2/mingw32.

**Comment by PikachuHy** [comment]
Qt4 has the QPainterPath header.
Theoretically, it works.
https://doc.qt.io/archives/qt-4.8/qpainterpath.html
https://doc.qt.io/qt-5/qpainterpath.html

**Comment by PikachuHy** [comment]
hi, I just test with qt4.8.7 on ubuntu 18.04.
it works well.

**Review by FlorianFranzen — APPROVED** [review]
Works as intended. Allows me to build 1.99.13 against 5.15 on NixOS. Thank you!

**Comment by sadhen** [comment]
Applied via `misc/admin/pr https://github.com/texmacs/texmacs/pull/43` manually.

**Pull request closed without merging**
