### PR TITLE
[SVN] fix technical spelling errors

### PR DESCRIPTION
**Pull request by jgmbenoit**
Description: upstream: fix: technical spelling errors
 This patch corrects some (very) technical spelling errors that were isolated by hand.
Origin: vendor, Debian
Author: Jerome Benoit < calculus _at_ debian _dot_ org >
Last-Update: 2024-08-08

### CODE REVIEW

**Comment by da-liii** [comment]
LGTM

**Comment by da-liii** [comment]
I have committed the language dic part, and still need to confirm that the fix on the scheme code is the correct fix.

**Comment by JackYansongLi** [comment]
The pull request is correct. Before the filx

```console
(string-convert "ì" "UTF-8" "LaTeX")
```
gets
```console
{\`i}
```

However, the output latex file does not apply the function provided. The exported latex file is

```console
\documentclass{article}
\usepackage[english]{babel}

\begin{document}

ì

\end{document}
```

**Comment by JackYansongLi** [comment]
I have ported it to mogan: https://github.com/XmacsLabs/mogan/pull/2012

**Comment by da-liii** [comment]
> However, the output latex file does not apply the function provided.

image

Switch the Character Encoding to ascii, and then you can test the output latex file with `string-convert` applied

Could you help test the TM -> LaTeX again with the option enabled?

**Comment by JackYansongLi** [comment]
> > However, the output latex file does not apply the function provided.
> 
> image
> 
> Switch the Character Encoding to ascii, and then you can test the output latex file with `string-convert` applied
> 
> Could you help test the TM -> LaTeX again with the option enabled?

The output is correct and string-convert function is successfully applied when the option is enabled

**Pull request closed without merging**
