### PR TITLE
S7 Integration for GNU TeXmacs 2.1

### PR DESCRIPTION
**Pull request by darcy-shen**
The pull request is adapt from https://github.com/mgubi/texmacs/pull/5
### Build: Using CMake on GNU/Linux
```
mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$HOME/software ..
make -j8
make install -j8
```

## Testing
Launch the built TeXmacs via:
```
$HOME/software/bin/texmacs
```

## Note
The author of this PR is Massimiliano Gubinelli (@mgubi) .

Joy Yang (@326623) and Darcy Shen (@darcy-shen ) are making improvements based on @mgubi 's work.

### CODE REVIEW

**Comment by 326623** [comment]
I have some fixes for the S7 scheme on my side for LaTeX export. Will try to make a pull request when I have time.

I also find some memory issues with S7 (allocating as large 540MB of heap size at times), making TeXmacs claiming above 1GB when I'm just editing a single 1 page tm document -- TeXmacs's memory stats give me: 170M. The rest, I assume it's on Qt.

Scheme function to probe memory usage: `(*s7* 'memory-usage)`. More on S7's doc website: https://ccrma.stanford.edu/software/snd/snd/s7.html.

**Comment by woutersj** [comment]
Before I compiled this branch with `-DCMAKE_BUILD_TYPE=Debug`, which worked fine. Now I built with `-DCMAKE_BUILD_TYPE=Release`, and I get an immediate segfault after starting TeXmacs. Any ideas what could be going on?

**Comment by 326623** [comment]
This patch may be of your interest: https://github.com/mgubi/texmacs/pull/5/commits/9475b125edf5a832eef9ea33fc110a3d95aefd01.

**Comment by 326623** [comment]
I think the high memory consumption problem stems from how S7 is managing its heap growth. It will double (x2) its heap size once its free-heap ratio reached certain thresholds after gc, which ended up pretty huge after a few iterations. My solution is to tweak it to x1.2~1.5, which seems to reduce the memory footprint of TeXmacs to around what Guile-1.8 would be using. This is at the cost of more gc (running a bit slower but using less memory), but I personally don't feel laggy while typing. So overall, it seems fine and reasonable. (I have been experimenting with it whilst doing my usual write -- have to restart every now and then, a bit painful I have to say.) Perhaps we can even dig into which portion of TeXmacs's Scheme code is increasing memory during editing to optimize memory consumption, but I'm pretty comfortable with what S7-TeXmacs is using right now.

**Comment by darcy-shen** [comment]
Closed by #65

**Pull request closed without merging**
