### PR TITLE
Implement subequations

### PR DESCRIPTION
**Pull request by woutersj**
This is an attempt to implement a subequations tag in which equations are numbered as (1a), (1b), (1c), etc.

### CODE REVIEW

**Comment by woutersj** [comment]
I'm afraid this solution doesn't play well with labels yet. Putting multiple labels in one subequations tag and referencing them doesn't produce the corresponding equation labels.

**Comment by woutersj** [comment]
Labels and references seem to work correctly now that `set-binding` is called for every label.

**Comment by sadhen** [comment]
I suggest that you should start a thread in the TeXmacs developers' mail list. Joris do not review PRs on github. I can only review PRs for a subset of GNU TeXmacs. 

For the dev mail list:
+ https://lists.gnu.org/archive/html/texmacs-dev/2021-01/threads.html
+ https://mail.gnu.org/mailman/listinfo/texmacs-dev

**Comment by pireddag** [comment]
> I suggest that you should start a thread in the TeXmacs developers' mail list. Joris do not review PRs on github.

This is also explained in the Readme on https://github.com/texmacs/texmacs, but I nonetheless feel that if there were a way to automate the process of "letting Joris know", it would be helpful. The best would be a system to transfer the pull requests automatically from Github to the TeXmacs patch system, but this might be impossible as these are based on two different versioning systems.

**Comment by woutersj** [comment]
Closing as this has been moved to and addressed on Savannah:
https://savannah.gnu.org/patch/?10026

**Pull request closed without merging**
